name: Build Signed Android Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Signed Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode Keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > ${{ runner.temp }}/release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # --- MODIFICATION 1: Clean Gradle Caches ---
      - name: Clean Gradle Caches
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -rf ~/.gradle/caches/*/plugin-resolution/

      - name: Generate Navigation Safe Args # Keep this separate
        run: ./gradlew :app:generateSafeArgsRelease --no-build-cache

      # --- MODIFICATION 2: Explicitly try compiling Kotlin ---
      # This is mainly for diagnosis - if this passes but assemble fails later,
      # it points to a different issue during packaging.
      - name: Compile Release Kotlin Sources
        run: ./gradlew :app:compileReleaseKotlin --no-build-cache --rerun-tasks

      # --- MODIFICATION 3: Build using --no-build-cache and --rerun-tasks ---
      - name: Build Release APK
        run: ./gradlew assembleRelease --no-build-cache --rerun-tasks
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          SIGNING_STORE_FILE: ${{ runner.temp }}/release.jks

      - name: Upload Signed Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Meme-ji-unzip-to-down-apk
          path: app/build/outputs/apk/release/Meme-ji-v*-release.apk
